export const getTestimonials = (t) => [
    {
        id: 1,
        name: t("testimonials.ahmed.name", { defaultValue: "Ahmed Khalil" }),
        title: t("testimonials.ahmed.title", { defaultValue: "Father of 3, Nasr City" }),
        quote: t("testimonials.ahmed.quote", { defaultValue: "كنت دايماً مفاجأة من الفاتورة، لكن كشف خلاني أعرف استهلاكي بالظبط وبقت تنبيهات قبل ما الفاتورة تزيد." }),
        initials: "AK",
        bgColor: "bg-blue-500/20",
        textColor: "text-blue-400",
    },
    {
        id: 2,
        name: t("testimonials.omar.name", { defaultValue: "Omar Samy" }),
        title: t("testimonials.omar.title", { defaultValue: "Business Owner, Alexandria" }),
        quote: t("testimonials.omar.quote", { defaultValue: "كنت مش عارف أحسب الفاتورة إزاي، كشف حل المشكلة وبي توصيات عملية بالذكاء الاصطناعي." }),
        initials: "OS",
        bgColor: "bg-emerald-500/20",
        textColor: "text-emerald-400",
    },
    {
        id: 3,
        name: t("testimonials.karim.name", { defaultValue: "Karim Hassan" }),
        title: t("testimonials.karim.title", { defaultValue: "Engineer, New Cairo" }),
        quote: t("testimonials.karim.quote", { defaultValue: "I was skeptical at first, but the real-time embedded system tracking is impressive. Saved 340 EGP on my last bill." }),
        initials: "KH",
        bgColor: "bg-purple-500/20",
        textColor: "text-purple-400",
    },
    {
        id: 4,
        name: t("testimonials.sara.name", { defaultValue: "Sara Mohamed" }),
        title: t("testimonials.sara.title", { defaultValue: "Housewife, Giza" }),
        quote: t("testimonials.sara.quote", { defaultValue: "التطبيق ساعدني أكتشف إن التكييف بيستهلك ضعف الطاقة المفروض. وفرت أكتر من 500 جنيه الشهر ده." }),
        initials: "SM",
        bgColor: "bg-rose-500/20",
        textColor: "text-rose-400",
    },
    {
        id: 5,
        name: t("testimonials.youssef.name", { defaultValue: "Youssef Adel" }),
        title: t("testimonials.youssef.title", { defaultValue: "Software Dev, Maadi" }),
        quote: t("testimonials.youssef.quote", { defaultValue: "The bill calculator finally makes sense of the tier system. No more surprises when the invoice lands." }),
        initials: "YA",
        bgColor: "bg-amber-500/20",
        textColor: "text-amber-400",
    },
    {
        id: 6,
        name: t("testimonials.nour.name", { defaultValue: "Nour El-Din" }),
        title: t("testimonials.nour.title", { defaultValue: "Shop Owner, Heliopolis" }),
        quote: t("testimonials.nour.quote", { defaultValue: "كشف بيفرق بين الاستهلاك التجاري والسكني. ده وفرلي كتير في التخطيط وأنا بحسب مصاريف المحل." }),
        initials: "NE",
        bgColor: "bg-cyan-500/20",
        textColor: "text-cyan-400",
    },
];